spring:
  datasource:
    url: jdbc:h2:file:./demo
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
#flyway:
#  url: jdbc:h2:file:./demo

